[colors.metadata]
name = "Everforest (Medium)"
mode = "Light"

[colors.generic]
surface = "#faf4ed"
background = "#fdf6e3"
overlay = "#efebd4"
foreground = "#5c6a72"
subtle = "#829181"
muted = "#939f91"
primary = "#8da101"
secondary = "#3a94c5"
success = "#8da101"
warning = "#dfa000"
failure = "#f85552"

[colors.terminal]
black = "#f2efdf"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
magenta = "#df69ba"
cyan = "#35a77c"
white = "#5c6a72"
bright_black = "#d3ceb2"
bright_red = "#ff807e"
bright_green = "#b9d500"
bright_yellow = "#ffbc13"
bright_blue = "#4db0e5"
bright_magenta = "#f586d2"
bright_cyan = "#32dd9b"
bright_white = "#7095aa"
color_16 = "#dbdbcf"
color_17 = "#c5c7bf"
color_18 = "#afb4af"
color_19 = "#9aa19f"
color_20 = "#858e90"
color_21 = "#707c81"
