[colors.metadata]
name = "Everforest (Hard)"
mode = "Dark"

[colors.generic]
surface = "#272e33"
background = "#2e383c"
overlay = "#414b50"
foreground = "#d3c6aa"
subtle = "#9da9a0"
muted = "#859289"
primary = "#a7c080"
secondary = "#7fbbb3"
success = "#a7c080"
warning = "#dbbc7f"
failure = "#e67e80"

[colors.terminal]
black = "#374145"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
bright_black = "#4a707f"
bright_red = "#f99ea0"
bright_green = "#c2df94"
bright_yellow = "#f1d59b"
bright_blue = "#92dbd1"
bright_magenta = "#eeb4d0"
bright_cyan = "#97dfa9"
bright_white = "#a99f87"
color_16 = "#4c5252"
color_17 = "#616460"
color_18 = "#77776e"
color_19 = "#8d8a7d"
color_20 = "#a49d8c"
color_21 = "#bbb29b"
