[colors.metadata]
name = "ï”¢ Gruvbox"
mode = "Light"

[colors.terminal]
black = "#f2e5bc"
red = "#af3a03"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#3c3836"
bright_black = "#fdecb2"
bright_blue = "#006c7f"
bright_cyan = "#2c8554"
bright_green = "#7d7b00"
bright_magenta = "#a83080"
bright_orange = "#c52d00"
bright_red = "#c52d00"
bright_white = "#433d3a"
bright_yellow = "#c37900"
color_16 = "#bab093"
color_17 = "#9f967f"
color_18 = "#857d6c"
color_19 = "#6b6559"
color_20 = "#534e47"
color_21 = "#3c3836"

[colors.generic]
background = "#f2e5bc"
base = "#f2e5bc"
surface = "#fff6db"
overlay = "#e1d4ac"
muted = "#000000"
subtle = "#000000"
text = "#3c3836"
primary = "#b57614"
secondary = "#79740e"
success = "#79740e"
warning = "#b57614"
failure = "#af3a03"
background_secondary = "#f4e8be"
background_tertiary = "#f2e5bc"
background_selection = "#eee0b7"
background_quaternary = "#ddccab"
text_secondary = "#7c6f64"
text_disabled = "#928374"
accent = "#b57614"
accent_secondary = "#af3a03"
