[colors.metadata]
name = "Gruvbox"
mode = "Dark"

[colors.generic]
surface = "#282828"
background = "#32302f"
overlay = "#32302f"
foreground = "#ebdbb2"
subtle = "#a89984"
muted = "#7c6f64"
primary = "#fabd2f"
secondary = "#b8bb26"
success = "#b8bb26"
warning = "#fabd2f"
failure = "#fb4934"

[colors.terminal]
black = "#45403d"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"
bright_black = "#7d6151"
bright_white = "#ceb982"
bright_red = "#ff7363"
bright_green = "#ebef25"
bright_yellow = "#ffce5d"
bright_blue = "#90cbb4"
bright_magenta = "#eca0b4"
bright_cyan = "#a5df90"
color_16 = "#5a544c"
color_17 = "#71695c"
color_18 = "#887e6d"
color_19 = "#a0957d"
color_20 = "#b8ac8f"
color_21 = "#d1c3a0"
