[colors.metadata]
name = "Gruvbox"
mode = "Light"

[colors.generic]
surface = "#fef7de"
background = "#fbf1c7"
overlay = "#f2e5bc"
foreground = "#3c3836"
subtle = "#7c6f64"
muted = "#928374"
primary = "#b57614"
secondary = "#af3a03"
success = "#79740e"
warning = "#b57614"
failure = "#af3a03"

[colors.terminal]
black = "#f2e5bc"
red = "#af3a03"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#3c3836"
bright_black = "#dac788"
bright_white = "#73594c"
bright_red = "#e54900"
bright_green = "#b9b001"
bright_yellow = "#fc9b00"
bright_blue = "#0094b2"
bright_magenta = "#cb3694"
bright_cyan = "#3cb46a"
color_16 = "#d6caa7"
color_17 = "#bab093"
color_18 = "#9f967f"
color_19 = "#857d6c"
color_20 = "#6b6559"
color_21 = "#534e47"
