[colors.metadata]
name = "Ros√© Pine Moon"
mode = "Dark"

[colors.generic]
surface = "#232136"
background = "#2a273f"
overlay = "#393552"
foreground = "#e0def4"
subtle = "#908caa"
muted = "#6e6a86"
primary = "#eb6f92"
secondary = "#3e8fb0"
success = "#3e8fb0"
warning = "#f6c177"
failure = "#eb6f92"

[colors.terminal]
black = "#393552"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"
bright_black = "#4d4390"
bright_red = "#fd90af"
bright_green = "#46b1dc"
bright_yellow = "#ffd8a1"
bright_blue = "#b8e7ef"
bright_magenta = "#dec9f8"
bright_cyan = "#fabcba"
bright_white = "#b1aed8"
color_16 = "#4f4a67"
color_17 = "#65617d"
color_18 = "#7c7894"
color_19 = "#9491ab"
color_20 = "#adaac3"
color_21 = "#c6c4db"
