[colors.metadata]
name = "Ros√© Pine Dawn"
mode = "Light"

[colors.generic]
surface = "#fffaf3"
background = "#faf4ed"
overlay = "#f2e9e1"
foreground = "#575279"
subtle = "#797593"
muted = "#9893a5"
primary = "#b4637a"
secondary = "#286983"
success = "#286983"
warning = "#ea9d34"
failure = "#b4637a"

[colors.terminal]
black = "#f2e9e1"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"
bright_black = "#d2c2b5"
bright_red = "#d7738f"
bright_green = "#1e92c0"
bright_yellow = "#ffb752"
bright_blue = "#5fb9c9"
bright_magenta = "#a988ce"
bright_cyan = "#ef9e99"
bright_white = "#6f64b3"
color_16 = "#dbd2d2"
color_17 = "#c4bbc2"
color_18 = "#aea5b3"
color_19 = "#988fa5"
color_20 = "#827a96"
color_21 = "#6c6687"
