[colors.metadata]
name = "Ros√© Pine"
mode = "Dark"

[colors.generic]
surface = "#191724"
background = "#1f1d2e"
overlay = "#26233a"
foreground = "#e0def4"
subtle = "#908caa"
muted = "#6e6a86"
primary = "#eb6f92"
secondary = "#31748f"
success = "#31748f"
warning = "#f6c177"
failure = "#eb6f92"

[colors.terminal]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"
bright_black = "#3c3376"
bright_red = "#fd90af"
bright_green = "#269ecd"
bright_yellow = "#ffd8a1"
bright_blue = "#b8e7ef"
bright_magenta = "#dec9f8"
bright_cyan = "#fadede"
bright_white = "#b1aed8"
color_16 = "#3d3a52"
color_17 = "#56526a"
color_18 = "#706c84"
color_19 = "#8b879f"
color_20 = "#a6a3bb"
color_21 = "#c3c0d7"
