[colors.metadata]
name = "ï”¢ Test"
mode = "Light"

[colors.terminal]
black = "#f2e9e1"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"
bright_black = "#d3c2b4"
bright_red = "#d67490"
bright_green = "#1e91c0"
bright_yellow = "#ffb75a"
bright_blue = "#60b9c9"
bright_magenta = "#a988ce"
bright_cyan = "#ef9d99"
bright_white = "#6f65b3"
color_16 = "#dbd2d2"
color_17 = "#c4bbc2"
color_18 = "#ada5b3"
color_19 = "#978fa5"
color_20 = "#817a96"
color_21 = "#6c6687"

[colors.generic]
surface = "#fffaf8"
background = "#faf6f3"
overlay = "#f2e9e1"
muted = "#928fa2"
subtle = "#767197"
foreground = "#575279"
success = "#286983"
warning = "#ea9d34"
failure = "#b4637a"
primary = "#d7827e"
secondary = "#ffb75a"
